version: "3.8"
services:

  node:
    build:
      context: .
      dockerfile: Node.DockerFile
    command: bash -c "yarn && yarn dev --host 0.0.0.0"
    ports:
      - "80:5173"
    volumes:
      - .:/jaroost-toolbox-components